USE
ARTHOUSE;
CREATE TABLE PRODUTO
(
    ID_PRODUTO           INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME_PRODUTO         VARCHAR(100),
    DESC_PRODUTO         VARCHAR(250),
    CONT_PRODUTO         LONGBLOB,
    ID_USUARIO_CRIACAO   INTEGER(10),
    DATA_CRIACAO         DATETIME,
    ID_USUARIO_ALTERACAO INTEGER(10),
    DATA_ALTERACAO       DATETIME,
    ID_TIPO_PRODUTO      INTEGER(10)
);

CREATE TABLE CORES_PRODUTO
(
    ID_COR_PRODUTO    INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME_COR_PRODUTO  VARCHAR(100),
    DESC_COR_PRODUTO  VARCHAR(200),
    IMG_CORES_PRODUTO BLOB
);

CREATE TABLE CARACTERISTICAS_PRODUTO
(
    ID_CARACTERISTICAS_PRODUTO   INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME_CARACTERISTICAS_PRODUTO VARCHAR(100),
    IMG_CARACTERISTICAS_PRODUTO  BLOB
);

CREATE TABLE TIPO_PRODUTO
(
    ID_TIPO_PRODUTO   INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME_TIPO_PRODUTO VARCHAR(100)
);

CREATE TABLE CORES_PRODUTO_PRODUTO
(
    ID_CORES_PRODUTO_PRODUTO INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_COR_PRODUTO           INTEGER,
    ID_PRODUTO               INTEGER,
    FOREIGN KEY (ID_COR_PRODUTO) REFERENCES CORES_PRODUTO (ID_COR_PRODUTO),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO)
);

CREATE TABLE CARACTERISTICA_PRODUTO_PRODUTO
(
    ID_CARACTERISTICA_PRODUTO_PRODUTO INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_CARACTERISTICAS_PRODUTO        INTEGER,
    ID_PRODUTO                        INTEGER,
    FOREIGN KEY (ID_CARACTERISTICAS_PRODUTO) REFERENCES CARACTERISTICAS_PRODUTO (ID_CARACTERISTICAS_PRODUTO),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO)

);

CREATE TABLE CLIENTE_LEAD
(
    ID_CLIENTE_LEAD         INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME_CLIENTE_LEAD       VARCHAR(100),
    ID_USUARIO_CRIACAO      INTEGER(10),
    DATA_CRIACAO            DATETIME,
    ID_USUARIO_ALTERACAO    INTEGER(10),
    DATA_ALTERACAO          DATETIME,
    ID_CONTATO_CLIENTE_LEAD INTEGER(10)
);


CREATE TABLE CONTATO_CLIENTE_LEAD
(
    ID_CONTATO_CLIENTE_LEAD INTEGER PRIMARY KEY AUTO_INCREMENT,
    EMAIL_CLIENTE_LEAD      VARCHAR(100),
    CELULAR_CLIENTE_LEAD    VARCHAR(30),
    ID_USUARIO_CRIACAO      INTEGER(10),
    DATA_CRIACAO            DATETIME,
    ID_USUARIO_ALTERACAO    INTEGER(10),
    DATA_ALTERACAO          DATETIME
);

CREATE TABLE MENSAGEM
(
    ID_MENSAGEM          INTEGER PRIMARY KEY AUTO_INCREMENT,
    ASSUNTO_MENSAGEM     VARCHAR(200),
    TEXT_MENSAGEM        LONGTEXT,
    ID_CLIENTE_LEAD      INTEGER(10),
    ID_USUARIO_CRIACAO   INTEGER(10),
    DATA_CRIACAO         DATETIME,
    ID_USUARIO_ALTERACAO INTEGER(10),
    DATA_ALTERACAO       DATETIME
);


ALTER TABLE PRODUTO
    ADD FOREIGN KEY (ID_TIPO_PRODUTO) REFERENCES TIPO_PRODUTO (ID_TIPO_PRODUTO);

ALTER TABLE CLIENTE_LEAD
    ADD FOREIGN KEY (ID_CONTATO_CLIENTE_LEAD) REFERENCES CONTATO_CLIENTE_LEAD (ID_CONTATO_CLIENTE_LEAD);

ALTER TABLE MENSAGEM
    ADD FOREIGN KEY (ID_CLIENTE_LEAD) REFERENCES CLIENTE_LEAD (ID_CLIENTE_LEAD);


INSERT INTO TIPO_PRODUTO(NOME_TIPO_PRODUTO)
VALUES ('Papel de Parede');
INSERT INTO TIPO_PRODUTO(NOME_TIPO_PRODUTO)
VALUES ('Adesivo de Parede');

INSERT INTO CARACTERISTICAS_PRODUTO(NOME_CARACTERISTICAS_PRODUTO)
VALUES ('3D');
INSERT INTO CARACTERISTICAS_PRODUTO(NOME_CARACTERISTICAS_PRODUTO)
VALUES ('Abstrato');
INSERT INTO CARACTERISTICAS_PRODUTO(NOME_CARACTERISTICAS_PRODUTO)
VALUES ('Arabesco');
INSERT INTO CARACTERISTICAS_PRODUTO(NOME_CARACTERISTICAS_PRODUTO)
VALUES ('Caligrafia');
INSERT INTO CARACTERISTICAS_PRODUTO(NOME_CARACTERISTICAS_PRODUTO)
VALUES ('Chevron');
INSERT INTO CARACTERISTICAS_PRODUTO(NOME_CARACTERISTICAS_PRODUTO)
VALUES ('Cidade');
INSERT INTO CARACTERISTICAS_PRODUTO(NOME_CARACTERISTICAS_PRODUTO)
VALUES ('Cimento Queimado');
INSERT INTO CARACTERISTICAS_PRODUTO(NOME_CARACTERISTICAS_PRODUTO)
VALUES ('Cortiça');
INSERT INTO CARACTERISTICAS_PRODUTO(NOME_CARACTERISTICAS_PRODUTO)
VALUES ('Floral e Flores');
INSERT INTO CARACTERISTICAS_PRODUTO(NOME_CARACTERISTICAS_PRODUTO)
VALUES ('Geométrico');
INSERT INTO CARACTERISTICAS_PRODUTO(NOME_CARACTERISTICAS_PRODUTO)
VALUES ('Infantil');
INSERT INTO CARACTERISTICAS_PRODUTO(NOME_CARACTERISTICAS_PRODUTO)
VALUES ('Listras');
INSERT INTO CARACTERISTICAS_PRODUTO(NOME_CARACTERISTICAS_PRODUTO)
VALUES ('Madeira');
INSERT INTO CARACTERISTICAS_PRODUTO(NOME_CARACTERISTICAS_PRODUTO)
VALUES ('Mineral (Mica)');
INSERT INTO CARACTERISTICAS_PRODUTO(NOME_CARACTERISTICAS_PRODUTO)
VALUES ('Natureza');
INSERT INTO CARACTERISTICAS_PRODUTO(NOME_CARACTERISTICAS_PRODUTO)
VALUES ('Pedras');
INSERT INTO CARACTERISTICAS_PRODUTO(NOME_CARACTERISTICAS_PRODUTO)
VALUES ('Texturas');
INSERT INTO CARACTERISTICAS_PRODUTO(NOME_CARACTERISTICAS_PRODUTO)
VALUES ('Tijolinhos');


INSERT INTO CORES_PRODUTO(NOME_COR_PRODUTO, DESC_COR_PRODUTO)
VALUES ('Amarelo', 'Tonalidade Amarelada');

INSERT INTO CORES_PRODUTO(NOME_COR_PRODUTO, DESC_COR_PRODUTO)
VALUES ('Azul', 'Tonalidade Aluzada');

INSERT INTO CORES_PRODUTO(NOME_COR_PRODUTO, DESC_COR_PRODUTO)
VALUES ('Champagne', 'Tonalidade Champagne');

INSERT INTO CORES_PRODUTO(NOME_COR_PRODUTO, DESC_COR_PRODUTO)
VALUES ('Cinza', 'Tonalidade Cinza');

INSERT INTO CORES_PRODUTO(NOME_COR_PRODUTO, DESC_COR_PRODUTO)
VALUES ('Dourado', 'Tonalidade Dourada');

INSERT INTO CORES_PRODUTO(NOME_COR_PRODUTO, DESC_COR_PRODUTO)
VALUES ('Laranja', 'Tonalidade Preta');

INSERT INTO CORES_PRODUTO(NOME_COR_PRODUTO, DESC_COR_PRODUTO)
VALUES ('Marrom', 'Tonalidade Laranja');

INSERT INTO CORES_PRODUTO(NOME_COR_PRODUTO, DESC_COR_PRODUTO)
VALUES ('Preto e Branco', 'Tonalidade Preto e Branco');

INSERT INTO CORES_PRODUTO(NOME_COR_PRODUTO, DESC_COR_PRODUTO)
VALUES ('Prata', 'Tonalidade Prata');

INSERT INTO CORES_PRODUTO(NOME_COR_PRODUTO, DESC_COR_PRODUTO)
VALUES ('Rosa e Lilás', 'Tonalidade Rosa e Lilás');

INSERT INTO CORES_PRODUTO(NOME_COR_PRODUTO, DESC_COR_PRODUTO)
VALUES ('Verde', 'Tonalidade Verde');

INSERT INTO CORES_PRODUTO(NOME_COR_PRODUTO, DESC_COR_PRODUTO)
VALUES ('Vermelho', 'Tonalidade Vermelho');



ALTER TABLE CARACTERISTICAS_PRODUTO
    ADD IMG_CARACTERISTICAS_PRODUTO LONGBLOB;

ALTER TABLE CORES_PRODUTO
    ADD IMG_CORES_PRODUTO LONGBLOB;


CREATE TABLE STATUS_PRODUTO
(
    ID_STATUS_PRODUTO   INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME_STATUS_PRODUTO VARCHAR(200)
);


ALTER TABLE PRODUTO
    ADD ID_STATUS_PRODUTO INTEGER(10);


ALTER TABLE PRODUTO
    ADD FOREIGN KEY (ID_STATUS_PRODUTO) REFERENCES STATUS_PRODUTO (ID_STATUS_PRODUTO);


INSERT INTO STATUS_PRODUTO(NOME_STATUS_PRODUTO)
VALUES ('Lançamentos');
INSERT INTO STATUS_PRODUTO(NOME_STATUS_PRODUTO)
VALUES ('Mais vendidos');
INSERT INTO STATUS_PRODUTO(NOME_STATUS_PRODUTO)
VALUES ('Normal');
